# Generated by Django 4.0.6 on 2022-09-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('number', models.CharField(max_length=12, verbose_name='Номер для связи')),
                ('comment_order', models.CharField(blank=True, max_length=500, verbose_name='Коментарии')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_change', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='обработанная заявка')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=255, verbose_name='Модель')),
                ('year_avto', models.DateField(null=True, verbose_name='Год производства автомобиля')),
                ('distance', models.CharField(default=' ', max_length=6, verbose_name='Пробег автомобиля')),
                ('content', models.TextField(blank=True, default=' ', verbose_name='Текст статьи')),
                ('photo', models.ImageField(default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo3', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo4', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo5', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Cars',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Client_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=' ', max_length=15, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(default=' ', max_length=50, verbose_name='Имя')),
                ('password', models.CharField(default=' ', max_length=10, verbose_name='Пароль')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('phone', models.CharField(default=' ', max_length=12, verbose_name='Номер телефона')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Client_ registrations',
                'verbose_name_plural': 'Зарегистрированные клиенты',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='Online_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('a', models.CharField(blank=True, max_length=100, verbose_name='Откуда')),
                ('b', models.CharField(blank=True, max_length=100, verbose_name='Куда')),
                ('date', models.DateField(null=True, verbose_name='Дата подачи автомобиля')),
                ('time_order', models.TimeField(null=True, verbose_name='Время подачи авто')),
                ('comment_driver', models.CharField(blank=True, max_length=500, verbose_name='Коментарии водителю')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('baby_chair', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('smoking', models.BooleanField(default=False, verbose_name='Курение в авто')),
                ('music', models.BooleanField(default=False, verbose_name='Музыка клиента')),
                ('cars', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.PROTECT, to='post.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Online_orders',
                'verbose_name_plural': 'Заказы с сайта',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=' ', max_length=70, verbose_name='Фамилия')),
                ('date_birth', models.DateField(null=True)),
                ('photo_person', models.ImageField(blank=True, default=' ', upload_to='driver/%Y/%m/%d/', verbose_name='Фото водителя')),
                ('content', models.TextField(blank=True, default=' ', verbose_name='Описание водителя')),
                ('education', models.CharField(default=' ', max_length=100, verbose_name='Образование')),
                ('language_person', models.CharField(default=' ', max_length=50, verbose_name='Знание языков')),
                ('driving_experience', models.DateField(null=True, verbose_name='Водительсктий стаж')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.car')),
            ],
            options={
                'verbose_name': 'Drivers',
                'verbose_name_plural': 'Водители автопарка',
                'ordering': ['first_name'],
            },
        ),
    ]
